"""Builds assets/deck.js: a sample of the app's own cards, every game, language and intensity.

    python3 tools/deck.py ../joy-ios

The sample is seeded, so the same decks give the same cards every time.
"""
import json
import os
import random
import sys

IOS = sys.argv[1] if len(sys.argv) > 1 else '../joy-ios'
SRC = os.path.join(IOS, 'Joy', 'Resources', 'Content')
OUT = os.path.join(os.path.dirname(__file__), '..', 'assets', 'deck.js')

# How many of each kind of card the page carries, per game and intensity.
GAMES = {
    'truthOrDare': ('truth-or-dare', {'truths': 9, 'dares': 9}),
    'neverHaveIEver': ('never-have-i-ever', {'statements': 14}),
    'wouldYouRather': ('would-you-rather', {'dilemmas': 12}),
    'mostLikelyTo': ('most-likely-to', {'prompts': 14}),
    'hotSeat': ('hot-seat', {'questions': 14}),
}


def fits(card):
    """Short enough to sit on a card on the page without shrinking."""
    if isinstance(card, dict):
        return len(card['a']) + len(card['b']) <= 110
    return len(card) <= 118


deck = {}
for lang in ['en', 'ka']:
    deck[lang] = {}
    for game, (name, kinds) in GAMES.items():
        content = json.load(open(os.path.join(SRC, f'{name}.{lang}.json'), encoding='utf-8'))
        deck[lang][game] = {}
        for level in ['light', 'bold', 'adult']:
            deck[lang][game][level] = {}
            for kind, count in kinds.items():
                pool = [card for card in content[level][kind] if fits(card)]
                rng = random.Random(f'{game}.{level}.{kind}.{lang}')
                deck[lang][game][level][kind] = rng.sample(pool, min(count, len(pool)))

with open(OUT, 'w', encoding='utf-8') as f:
    f.write("/* Joy: a sample of the app's own cards, copied from joy-ios Resources/Content.\n"
            "   Each language is its own deck, written for its own players. Generated by tools/deck.py, do not edit by hand. */\n")
    f.write('window.JOY_DECK = ' + json.dumps(deck, ensure_ascii=False, indent=1) + ';\n')
print(f'wrote {OUT}')
